engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.json"
  - "**.module"
exclude_paths: []
